# Generated by Django 5.0.1 on 2026-02-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total credit limit', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current outstanding balance', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='minimum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='payment_due_date',
            field=models.IntegerField(blank=True, help_text='Day of month for payment due (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='statement_date',
            field=models.IntegerField(blank=True, help_text='Day of month for statement (1-31)', null=True),
        ),
    ]
