# Generated by Django 4.2.16 on 2026-04-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_webauthn_credential'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webauthncredential',
            new_name='webauthn_cr_user_id_7a1b97_idx',
            old_name='api_webauthn_user_id_idx',
        ),
        migrations.AddField(
            model_name='card',
            name='card_category',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('signature', 'Signature'), ('infinite', 'Infinite'), ('titanium', 'Titanium'), ('business', 'Business'), ('world', 'World'), ('world_elite', 'World Elite')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='minimum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed minimum amount (optional if percentage set)', max_digits=15, null=True),
        ),
    ]
