# Generated by Django 4.2.16 on 2026-04-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_ownership',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('supplementary', 'Supplementary'), ('joint', 'Joint')], max_length=50, null=True),
        ),
    ]
