# Generated by Django 4.2.16 on 2026-04-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_card_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
