# Generated by Django 4.2.16 on 2026-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_last_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='annual_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='fee_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='has_waiver_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='late_payment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='over_limit_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='renewal_type',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('conditional', 'Conditional')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='supplementary_card_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='waiver_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
