# Generated by Django 4.2.16 on 2026-04-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_fees_renewal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='account_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='account_manager_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='bank_emails',
            field=models.TextField(blank=True, help_text='JSON array of bank email addresses', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_replacement_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
